### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by tabam1** [Step7750/node-csgo-cdn#13] opened 2019-02-16 09:24 UTC
Can you update this ? Not work with current node-user version.

**Comment by Step7750** [comment] 2019-02-16 16:46
Please be more specific

**Comment by tabam1** [comment] 2019-02-16 17:23
NOT working :)

**Comment by Step7750** [comment] 2019-02-16 17:24
Stack trace, details?

**Comment by iDefineHD** [comment] 2019-02-16 17:24
Also, maybe a code snippet. As you may not be calling it correctly.

**Comment by tabam1** [comment] 2019-02-16 17:29
cdn.on('ready', () => {
	console.log('ready test');


no log, it is not performed

**Comment by tabam1** [comment] 2019-02-16 17:31
```
const SteamUser = require('steam-user');
const csgoCDN = require('csgo-cdn');

const cred = {
    username: 'myname',
    password: 'mypass'
};

const user = new SteamUser({enablePicsCache: true});
const cdn = new csgoCDN(user, {musicKits: true, cases: true, tools: true, statusIcons: true, logLevel: 'debug'});

cdn.on('ready', () => {
	console.log('ready test');
    console.log(cdn.getStickerURL('cologne2016/astr_gold', false));
    console.log(cdn.getStickerURL('cologne2016/astr_gold', true));
});


    const loginDetails = {
        accountName: cred.username,
        password: cred.password,
        rememberPassword: true
    };

    console.log('Logging into Steam....');

    user.logOn(loginDetails);

user.on('loggedOn', () => {
    console.log('Logged onto Steam');
});

user.on('contentServersReady', () => {
    console.log('Content servers ready');
});
```

**Comment by Step7750** [comment] 2019-02-16 17:33
Look at the example, you need to login outside of the cdn ready event.

**Comment by tabam1** [comment] 2019-02-16 17:36
What ? I use example and not working

**Comment by Step7750** [comment] 2019-02-16 17:43
Does the account own csgo?

**Comment by tabam1** [comment] 2019-02-16 17:44
yes

**Comment by tabam1** [comment] 2019-02-16 17:46
It does not come: `cdn.on('ready', () => {`

**Comment by tabam1** [comment] 2019-02-16 17:50
in my opinion it does not work because the steam-user was modified

**Comment by Step7750** [comment] 2019-02-17 23:42
I just cloned the repo and tried the example with a newly generated account that owns CS:GO; everything worked as intended. Therefore, I'm going to close this issue unless you can provide more details.

**Closed by Step7750** 2019-02-17 23:42 UTC
